# Generated by Django 2.2 on 2020-07-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_rest_api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
